### PR TITLE
Repeatability: Use new seedable random

### PR DESCRIPTION
**Pull request by michaschwab**
This provides a seedable random function, and uses it in the positions initialization code of d3-voronoi-map. The seedable random function is non-seeded by default, meaning that the default behavior of random position is unchanged if no seed is set.

To switch to the stable and repeatable mode, do:
```
import * as d3voronoiMap from 'd3-voronoi-map'; // Or however else you import d3-voronoi-map.
d3voronoiMap.voronoiMapInitialPositionRandomSeed.seed(1234); // Some number.
d3voronoiMap.voronoiMap(); // Or however else you use d3-voronoi-map.
```
Example: https://www.youtube.com/watch?v=vtSfz0WFZ1g

Related issues: https://github.com/Kcnarf/d3-voronoi-treemap/issues/4 and https://github.com/Kcnarf/d3-voronoi-map/issues/2

### CODE REVIEW

**Comment by michaschwab** [comment]
Sorry, I realized that this does not work with the newest patch because something changed in how the random positions are generated. I had tried it on a previous version. Looking into why this isn't generating a stable result right now, will fix soon.

**Comment by Kcnarf** [comment]
This is a great improvement.
Unfortunatly I'll not be able to check it before 13th aug. 2018.

**Comment by Kcnarf** [comment]
After some googling and experiments, I found a preferable way to make d3-voronoi-map producing repeatable arrangements: enhance  the plugin with a new API allowing the user to set is preferred prng.

Why I think using an external prng its a better way:
1. the seedable prng is no longer included in the plugin, meaning it has no longer to be maintained
1. by using external prngs (like [seedrandom](https://github.com/davidbau/seedrandom)), the user can _de facto_ use other useful prngs' features (reseeding, saving/restoring state, ...)
1. by using external prngs, the user can use a prng based on non-uniform distributions (cf. [d3-random](https://github.com/d3/d3-random), which also offers the possibility to use a seedable prng _via_ its _source_ API)

The drawback I'm thinking of is that the plugin do not ensure that the used prng mimic the `Math.random` behaviour (i.e. responds to the `()` call with a number in [0,1[). Nevertheless,  this seems almost obvious to any coder, and thus not a big drawback.

The [repeatability](https://github.com/Kcnarf/d3-voronoi-map/tree/repeatability) branch defines the 'prng' API, and is ready to be merged:
. build accessible through `<script src="https://raw.githack.com/Kcnarf/d3-voronoi-map/repeatability/build/d3-voronoi-map.js"></script>`
. [documentation/usage](https://github.com/Kcnarf/d3-voronoi-map/tree/repeatability#voronoiMap_prng)

Can you give me your thoughts?

**Comment by Kcnarf** [comment]
OK.
I'm definitely convinced that introducing an API allowing the user to set is preferred prng is the best solution, both in terms of maintainability, concerns and evolutivity.

Master has been updated in consequence. Next version 1.2.0 will provide this API, named `prng`.

Nonetheless, thanks for your time and engagement. It gives me the possibility to dig into the repeatability/reproductibility feature.

**Pull request closed without merging**
