### PR TITLE
Comment out console.log

### LINKED ISSUE #6: Get rid of console.log in production
Code line: https://github.com/Kcnarf/d3-voronoi-map/blob/master/src/flickering-mitigation.js#L129

It logs `flickering mitigation ratio: X.XX` when really it shouldn't unless in development mode

### PR DESCRIPTION
**Pull request by marcofugaro**
Close #6, it's really annoying when using the library.

I didn't generate the .min.js because there is no script in the build pipeline to generate it.

### CODE REVIEW

**Comment by Kcnarf** [comment]
> Close #6, it's really annoying when using the library.
> 
> I didn't generate the .min.js because there is no script in the build pipeline to generate it.

Before commiting, `yarn precommit' builds the minified file (after executing tests and building basic non-minified files).

This is available at the end of the README, but it seems it is not obvious. Can you give me some advices in order to make it more explicit.

**Comment by marcofugaro** [comment]
@Kcnarf I would move the minifying script in the `postbuild` script in the package.json scripts. This will get executed after the `build` command has finished

**Comment by marcofugaro** [comment]
@Kcnarf also, it would be great if you'd publish a new version of this library on npm with those fixes 🙂

**Comment by Kcnarf** [comment]
> @Kcnarf also, it would be great if you'd publish a new version of this library on npm with those fixes 🙂

new version 2.0.***1*** is available on NPM

**Pull request merged**
